version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR"
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 581891202819.dkr.ecr.eu-north-1.amazonaws.com

  build:
    commands:
      - echo "Building JAR"
      - mvn clean package
      - echo "Building Docker image"
      - docker build -t monitoring-app .
      - docker tag monitoring-app:latest 581891202819.dkr.ecr.eu-north-1.amazonaws.com/monitoring-app:latest

  post_build:
    commands:
      - echo "Pushing image"
      - docker push 581891202819.dkr.ecr.eu-north-1.amazonaws.com/monitoring-app:latest
      - echo "Creating imagedefinitions.json"
      - printf '[{"name":"monitoring-app","imageUri":"%s"}]' 581891202819.dkr.ecr.eu-north-1.amazonaws.com/monitoring-app:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
