version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - chmod +x monitoring-app/mvnw
      - monitoring-app/mvnw clean package -DskipTests

artifacts:
  files:
    - monitoring-app/target/*.jar
  discard-paths: yes
